# Generated by Django 3.1.1 on 2020-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Skills', models.TextField()),
                ('Email', models.CharField(max_length=100)),
                ('Mobile_number', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('Address', models.TextField()),
            ],
        ),
    ]
